// Generated by gencpp from file base_joy_controller_pkg/modes.msg
// DO NOT EDIT!


#ifndef BASE_JOY_CONTROLLER_PKG_MESSAGE_MODES_H
#define BASE_JOY_CONTROLLER_PKG_MESSAGE_MODES_H

#include <ros/service_traits.h>


#include <base_joy_controller_pkg/modesRequest.h>
#include <base_joy_controller_pkg/modesResponse.h>


namespace base_joy_controller_pkg
{

struct modes
{

typedef modesRequest Request;
typedef modesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct modes
} // namespace base_joy_controller_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::base_joy_controller_pkg::modes > {
  static const char* value()
  {
    return "2bc158173e2185ec21215d46ee65d595";
  }

  static const char* value(const ::base_joy_controller_pkg::modes&) { return value(); }
};

template<>
struct DataType< ::base_joy_controller_pkg::modes > {
  static const char* value()
  {
    return "base_joy_controller_pkg/modes";
  }

  static const char* value(const ::base_joy_controller_pkg::modes&) { return value(); }
};


// service_traits::MD5Sum< ::base_joy_controller_pkg::modesRequest> should match
// service_traits::MD5Sum< ::base_joy_controller_pkg::modes >
template<>
struct MD5Sum< ::base_joy_controller_pkg::modesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::base_joy_controller_pkg::modes >::value();
  }
  static const char* value(const ::base_joy_controller_pkg::modesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_joy_controller_pkg::modesRequest> should match
// service_traits::DataType< ::base_joy_controller_pkg::modes >
template<>
struct DataType< ::base_joy_controller_pkg::modesRequest>
{
  static const char* value()
  {
    return DataType< ::base_joy_controller_pkg::modes >::value();
  }
  static const char* value(const ::base_joy_controller_pkg::modesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::base_joy_controller_pkg::modesResponse> should match
// service_traits::MD5Sum< ::base_joy_controller_pkg::modes >
template<>
struct MD5Sum< ::base_joy_controller_pkg::modesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::base_joy_controller_pkg::modes >::value();
  }
  static const char* value(const ::base_joy_controller_pkg::modesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_joy_controller_pkg::modesResponse> should match
// service_traits::DataType< ::base_joy_controller_pkg::modes >
template<>
struct DataType< ::base_joy_controller_pkg::modesResponse>
{
  static const char* value()
  {
    return DataType< ::base_joy_controller_pkg::modes >::value();
  }
  static const char* value(const ::base_joy_controller_pkg::modesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASE_JOY_CONTROLLER_PKG_MESSAGE_MODES_H
