// Generated by gencpp from file base_joy_controller_pkg/modesRequest.msg
// DO NOT EDIT!


#ifndef BASE_JOY_CONTROLLER_PKG_MESSAGE_MODESREQUEST_H
#define BASE_JOY_CONTROLLER_PKG_MESSAGE_MODESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_joy_controller_pkg
{
template <class ContainerAllocator>
struct modesRequest_
{
  typedef modesRequest_<ContainerAllocator> Type;

  modesRequest_()
    : mode()  {
    }
  modesRequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct modesRequest_

typedef ::base_joy_controller_pkg::modesRequest_<std::allocator<void> > modesRequest;

typedef boost::shared_ptr< ::base_joy_controller_pkg::modesRequest > modesRequestPtr;
typedef boost::shared_ptr< ::base_joy_controller_pkg::modesRequest const> modesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::base_joy_controller_pkg::modesRequest_<ContainerAllocator1> & lhs, const ::base_joy_controller_pkg::modesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::base_joy_controller_pkg::modesRequest_<ContainerAllocator1> & lhs, const ::base_joy_controller_pkg::modesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace base_joy_controller_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e84dc3ad5dc323bb64f0aca01c2d1eef";
  }

  static const char* value(const ::base_joy_controller_pkg::modesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe84dc3ad5dc323bbULL;
  static const uint64_t static_value2 = 0x64f0aca01c2d1eefULL;
};

template<class ContainerAllocator>
struct DataType< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_joy_controller_pkg/modesRequest";
  }

  static const char* value(const ::base_joy_controller_pkg::modesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mode\n"
;
  }

  static const char* value(const ::base_joy_controller_pkg::modesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct modesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_joy_controller_pkg::modesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_joy_controller_pkg::modesRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_JOY_CONTROLLER_PKG_MESSAGE_MODESREQUEST_H
