// Generated by gencpp from file base_joy_controller_pkg/modesResponse.msg
// DO NOT EDIT!


#ifndef BASE_JOY_CONTROLLER_PKG_MESSAGE_MODESRESPONSE_H
#define BASE_JOY_CONTROLLER_PKG_MESSAGE_MODESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_joy_controller_pkg
{
template <class ContainerAllocator>
struct modesResponse_
{
  typedef modesResponse_<ContainerAllocator> Type;

  modesResponse_()
    : currmode()  {
    }
  modesResponse_(const ContainerAllocator& _alloc)
    : currmode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _currmode_type;
  _currmode_type currmode;





  typedef boost::shared_ptr< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct modesResponse_

typedef ::base_joy_controller_pkg::modesResponse_<std::allocator<void> > modesResponse;

typedef boost::shared_ptr< ::base_joy_controller_pkg::modesResponse > modesResponsePtr;
typedef boost::shared_ptr< ::base_joy_controller_pkg::modesResponse const> modesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::base_joy_controller_pkg::modesResponse_<ContainerAllocator1> & lhs, const ::base_joy_controller_pkg::modesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.currmode == rhs.currmode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::base_joy_controller_pkg::modesResponse_<ContainerAllocator1> & lhs, const ::base_joy_controller_pkg::modesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace base_joy_controller_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3154883b4f10b319a4642ede3be2af2e";
  }

  static const char* value(const ::base_joy_controller_pkg::modesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3154883b4f10b319ULL;
  static const uint64_t static_value2 = 0xa4642ede3be2af2eULL;
};

template<class ContainerAllocator>
struct DataType< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_joy_controller_pkg/modesResponse";
  }

  static const char* value(const ::base_joy_controller_pkg::modesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string currmode\n"
;
  }

  static const char* value(const ::base_joy_controller_pkg::modesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.currmode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct modesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_joy_controller_pkg::modesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_joy_controller_pkg::modesResponse_<ContainerAllocator>& v)
  {
    s << indent << "currmode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.currmode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_JOY_CONTROLLER_PKG_MESSAGE_MODESRESPONSE_H
